import type { Project } from './types';
export function practiceText(p:Project,change=''){
 const get=(id:string,fallback:string)=>p.session.history.find(s=>s.stepId===id)?.label||fallback;
 const subject=get('subject','possibility'),mood=get('mood','Happy & bright'),style=get('style','a garden');
 if(p.journey.capability==='generate_music')return `A Little More Light\n\nA song idea about ${subject.toLowerCase()}\n\nVerse\nThere’s a little more light when you’re near,\nA little more music for me to hear.\nTake an ordinary day, let it shine,\nThere’s a whole wide world in this heart of mine.\n\nChorus\nHere we are, here we go,\nMaking something only we could know.\nStep by step and line by line,\nThis little moment is yours and mine.\n\nMusical direction: ${mood.toLowerCase()}, ${style.toLowerCase()}.`;
 if(p.journey.id==='card')return `${subject==='A birthday'?'Happy birthday!':subject==='To say thank you'?'Thank you, from the heart':subject==='Thinking of you'?'A little note, just for you':'Here’s to you!'}\n\nTo ${mood.toLowerCase()},\n\n${change==='more-funny'?'You make ordinary days extraordinary—and even Mondays almost bearable.':change==='shorter'?'You make the world a little brighter.':'Some people make the world feel warmer just by being in it. You are one of those people.'}\n\nWith love`;
 if(p.journey.id==='printable')return `A Little Possibility\n\nA quiet page.\nAn open door.\nA little room\nfor something more.\n\nA thought takes shape.\nA color sings.\nThe smallest start\ncan grow its wings.\n\n${style==='Friendship'?'And when a friend is by your side,\nThe world feels warm and open wide.':'There’s no one way\nto make a start.\nJust follow what\nis in your heart.'}`;
 const place=style.toLowerCase();
 return `The Door That Wasn’t There Before\n\nIn ${place}, there was a door that nobody had noticed before. It stood between two old trees, painted the exact blue of the sky after rain.\n\nMara found it on a morning when she had gone out looking for ${subject.toLowerCase()}. A small brass sign on the door read: “Bring something only you can bring.”\n\nShe checked her pockets. A smooth stone. A piece of string. Half a biscuit. None of them seemed quite right.\n\nFrom the other side came a soft knock.\n\n“Are you coming in?” asked a voice.\n\n“I don’t have anything special,” Mara said.\n\nThere was a thoughtful pause. “Have you ever seen the world exactly the way you see it?”\n\nMara smiled. She pressed her hand against the blue wood and thought of the things she loved: a warm light in a window, a friend arriving early, the brave green of a leaf in spring.\n\nThe door swung open. Inside was a room full of unfinished things. A song without its last note. A story waiting for an ending. A painting with a space the shape of a new idea.\n\n${change==='different-ending'?'Mara left the door open for everyone who would come after her. Above it, she hung a new sign: “You already have what you need.”':change==='more-funny'?'A fox in an enormous hat bowed. “We’ve been expecting you,” it said. “Although we did also expect a biscuit.” Mara laughed and offered it half.':'Mara picked up a brush. She did not know exactly what she would make. For the first time that morning, that felt like a wonderful place to begin.'}\n\n${change==='shorter'?'': 'When she stepped outside again, the place looked the same. But she carried something new: the knowledge that a small beginning could open a very large door.'}`;
}
// A transparent, deterministic instrumental sketch. This is not a vocal or AI model.
export function composeSketch(seed:number,style:string,mood:string,change:string):Uint8Array {
 const sampleRate=16000,bpm=change==='more-upbeat'?125:change==='gentler'?74:mood.includes('gentle')?80:108;
 const beat=60/bpm,beats=32,seconds=beats*beat+1,n=Math.ceil(seconds*sampleRate),samples=new Float32Array(n);
 const minor=mood.includes('heartfelt'),scale=minor?[0,2,3,5,7,8,10]:[0,2,4,5,7,9,11];let random=seed>>>0;
 const next=()=>{random=(Math.imul(random,1664525)+1013904223)>>>0;return random/4294967296;};
 function note(midi:number,start:number,length:number,amp:number){const frequency=440*2**((midi-69)/12),from=Math.floor(start*sampleRate),to=Math.min(n,Math.floor((start+length)*sampleRate));for(let i=from;i<to;i++){const t=(i-from)/sampleRate;const attack=Math.min(1,t/.015),release=Math.min(1,(length-t)/.12),decay=Math.exp(-t*(style.includes('piano')?3:2));const wave=Math.sin(2*Math.PI*frequency*t)+.2*Math.sin(4*Math.PI*frequency*t)+.08*Math.sin(6*Math.PI*frequency*t);samples[i]+=wave*amp*attack*release*decay;}}
 const roots=[48,53,55,48];for(let b=0;b<beats;b++){const root=roots[Math.floor(b/4)%4];if(b%4===0){note(root,b*beat,beat*3.7,.13);note(root+(minor?3:4),b*beat,beat*3.7,.07);note(root+7,b*beat,beat*3.7,.06);}note(60+scale[Math.floor(next()*scale.length)],b*beat,beat*.85,.17);if(style.includes('pop')||style.includes('rock'))note(36,b*beat,.14,.1);}
 const bytes=new Uint8Array(44+n*2),view=new DataView(bytes.buffer);const str=(o:number,s:string)=>Array.from(s).forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));str(0,'RIFF');view.setUint32(4,36+n*2,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,n*2,true);for(let i=0;i<n;i++)view.setInt16(44+i*2,Math.max(-1,Math.min(1,samples[i]))*32767,true);return bytes;
}
