import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import type { Artifact, Project } from './types';
import { journeys } from './journeys';
export type Runtime = {DB:D1Database;FILES:R2Bucket;ADMIN_EMAIL?:string;APP_ENCRYPTION_KEY?:string;OPENAI_API_KEY?:string;ELEVENLABS_API_KEY?:string;OPENAI_TEXT_MODEL?:string;OPENAI_IMAGE_MODEL?:string;ELEVENLABS_MUSIC_MODEL?:string;ELEVENLABS_VOICE_MODEL?:string};
export const runtime = ()=> env as unknown as Runtime;
export const db=()=>runtime().DB;
export class PublicError extends Error { constructor(message:string,public status=400){super(message);} }
export async function user(){const u=await getChatGPTUser();if(!u)throw new PublicError('Please sign in to keep creating.',401);return u;}
export async function admin(){const u=await user();if(!isAdmin(u.email))throw new PublicError('This area is for the studio administrator.',403);return u;}
export function isAdmin(email:string){return !!runtime().ADMIN_EMAIL&&email.toLowerCase()===runtime().ADMIN_EMAIL?.toLowerCase();}
export function protectMutation(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new PublicError('Please return to the studio and try again.',403);if(request.headers.get('sec-fetch-site')==='cross-site')throw new PublicError('Please return to the studio.',403);if(!request.headers.get('content-type')?.includes('application/json'))throw new PublicError('Please use the studio controls.',415);}
export async function body(request:Request){if(Number(request.headers.get('content-length')||0)>50000)throw new PublicError('That is a little too much text. Please shorten it.');const raw=await request.text();if(raw.length>50000)throw new PublicError('Please shorten the text.');try{return JSON.parse(raw);}catch{throw new PublicError('That choice could not be read. Please try again.');}}
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
export function failure(e:unknown){return json({error:e instanceof PublicError?e.message:'That didn’t work. Your saved work is safe. Please try again.'},e instanceof PublicError?e.status:500);}
export function eventStatement(owner:string,projectId:string|null,type:string,payload:unknown={}){return db().prepare('INSERT INTO interaction_events (id,owner,project_id,type,payload,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,projectId,type,JSON.stringify(payload),new Date().toISOString());}
export async function getJourneys(includeHidden=false){const versions=await db().prepare('SELECT * FROM journey_versions ORDER BY version DESC').all<{journey_id:string;version:number;definition:string;published:number}>();const settings=await db().prepare('SELECT journey_id FROM journey_settings WHERE hidden=1').all<{journey_id:string}>();const hidden=new Set(settings.results.map(s=>s.journey_id));const result=new Map(journeys.map(j=>[j.id,j]));const seen=new Set<string>();for(const row of versions.results){if((row.published||includeHidden)&&!seen.has(row.journey_id)){result.set(row.journey_id,JSON.parse(row.definition));seen.add(row.journey_id);}}return [...result.values()].filter(j=>includeHidden||!hidden.has(j.id));}
export async function getProject(id:string,owner:string):Promise<Project>{const row=await db().prepare('SELECT * FROM projects WHERE id=? AND owner=?').bind(id,owner).first<Record<string,unknown>>();if(!row)throw new PublicError('That creation could not be found.',404);const rows=await db().prepare('SELECT payload FROM artifacts WHERE project_id=? ORDER BY created_at,id').bind(id).all<{payload:string}>();const generation=await db().prepare('SELECT id,error,status,updated_at FROM generations WHERE project_id=? ORDER BY created_at DESC LIMIT 1').bind(id).first<{id:string;error:string;status:string;updated_at:string}>();return {id,title:String(row.title),journey:JSON.parse(String(row.journey)),session:JSON.parse(String(row.session)),status:row.status as Project['status'],kept:!!row.kept,activeArtifactId:row.active_artifact_id as string|undefined,version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at),artifacts:rows.results.map(r=>JSON.parse(r.payload) as Artifact),generationId:generation?.id,error:generation?.error||undefined};}
export async function listProjects(owner:string){const ids=await db().prepare('SELECT id FROM projects WHERE owner=? ORDER BY updated_at DESC LIMIT 100').bind(owner).all<{id:string}>();return Promise.all(ids.results.map(r=>getProject(r.id,owner)));}
async function vault(){const hex=runtime().APP_ENCRYPTION_KEY;if(!hex||!/^[a-f0-9]{64}$/.test(hex))throw new PublicError('Secure provider setup is not available yet.',503);return crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g)!,x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encrypt(key:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await vault(),new TextEncoder().encode(key));return [...iv,...new Uint8Array(encrypted)].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function provider(id:'openai-text'|'openai-image'|'elevenlabs'|'elevenlabs-music'){const row=await db().prepare('SELECT encrypted_key,model FROM provider_settings WHERE id=?').bind(id).first<{encrypted_key:string;model:string}>();if(row){const data=Uint8Array.from(row.encrypted_key.match(/../g)!,h=>parseInt(h,16));const key=new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:data.slice(0,12)},await vault(),data.slice(12)));return {key,model:row.model};}const e=runtime();if(id==='elevenlabs-music')return {key:e.ELEVENLABS_API_KEY,model:e.ELEVENLABS_MUSIC_MODEL||'music_v2'};if(id==='elevenlabs')return {key:e.ELEVENLABS_API_KEY,model:e.ELEVENLABS_VOICE_MODEL||'eleven_multilingual_v2'};return id==='openai-image'?{key:e.OPENAI_API_KEY,model:e.OPENAI_IMAGE_MODEL||'gpt-image-1'}:{key:e.OPENAI_API_KEY,model:e.OPENAI_TEXT_MODEL||'gpt-6-astra'};}
export async function availability(){const [text,image,music]=await Promise.all([provider('openai-text'),provider('openai-image'),provider('elevenlabs-music')]);return {generate_music:!!music.key,generate_text:!!text.key,generate_image:!!image.key,create_printable:!!text.key};}
