'use client';
import { useEffect,useState } from 'react';
import { ArrowDown,ArrowLeft,ArrowUp,Check,Eye,Plus,Save,X } from 'lucide-react';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import Guide from './guide';
import { choose,goBack,validateJourney } from '@/lib/creative/engine';
import { capabilityLabels,journeys as builtins } from '@/lib/creative/journeys';
import type { Capability,Journey,Session } from '@/lib/creative/types';
function Picker({value,options,label,onChange}:{value:string;options:{value:string;label:string}[];label:string;onChange:(v:string)=>void}){return <Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="admin-select" aria-label={label}><SelectValue>{options.find(o=>o.value===value)?.label||value}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem className="admin-select-item" key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
type Data={journeys:Journey[];hidden:string[];availability:Record<Capability,boolean>;logs:{capability:string;provider:string;status:string;error?:string;created_at:string}[];versions:{journey_id:string;version:number;published:number}[]};
export default function Admin(){const [data,setData]=useState<Data|null>(null),[draft,setDraft]=useState<Journey|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(false),[session,setSession]=useState<Session|null>(null);
 async function load(){const r=await fetch('/api/admin');const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function send(body:unknown){setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);await load();setMessage('Saved.');return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 function edit(j:Journey){setDraft(structuredClone(j));setError('');setMessage('');}
 function changeStep(i:number,patch:Record<string,unknown>){if(draft)setDraft({...draft,steps:draft.steps.map((s,n)=>n===i?{...s,...patch}:s)});}
 function move(i:number,by:number){if(!draft)return;const steps=[...draft.steps];[steps[i],steps[i+by]]=[steps[i+by],steps[i]];setDraft({...draft,steps});}
 function beginPreview(){if(!draft)return;const errors=validateJourney(draft);if(errors.length){setError(errors.join(' '));return;}setSession({node:draft.start,history:[],seed:42});setPreview(true);}
 return <div><header className="site-header"><a className="wordmark" href="/">creative<br/><span>companion.</span></a><a className="button secondary" href="/"><ArrowLeft/> Back to the studio</a></header><main className="main-content admin-main"><p className="eyebrow">BEHIND THE SCENES</p><h1>Manage the studio</h1><p className="intro">Creative journeys and their connections. Visible only to the administrator.</p>{error&&<p role="alert" className="error-notice">{error}</p>}{message&&<p role="status" className="success-notice"><Check/>{message}</p>}
 <section className="admin-section"><h2>Creative connections</h2><p>API keys are stored as private environment variables in Netlify and are never sent to the browser or saved in this application’s database. Generation requests are capped at 30 per user each day.</p><div className="connection-status">{Object.entries(capabilityLabels).map(([id,label])=><div key={id}><span className={data?.availability[id as Capability]?'status-dot ready':'status-dot'}/><span>{label}</span><strong>{data?.availability[id as Capability]?'Connected':'Needs connection'}</strong></div>)}</div>
 <p className="setting-note">Add or change connections in Netlify under Project configuration → Environment variables, then redeploy. Complete songs use the official <a href="https://elevenlabs.io/docs/api-reference/music/compose" target="_blank" rel="noreferrer">Eleven Music API</a>. Writing and artwork use <a href="https://developers.openai.com/api/docs" target="_blank" rel="noreferrer">OpenAI</a>.</p></section>
 <section className="admin-section"><div className="admin-section-heading"><h2>Journey Builder</h2><button className="button secondary" onClick={()=>edit({...structuredClone(builtins[1]),id:`journey-${Date.now()}`,title:'A new creative journey',description:'Something new to make.',version:1})}><Plus/> New journey</button></div><div className="journey-list">{data?.journeys.map(j=><div key={j.id}><div><strong>{j.title}</strong><p>Version {j.version} · {data.hidden.includes(j.id)?'Unpublished':data.versions.some(v=>v.journey_id===j.id&&v.version===j.version&&!v.published)?'Latest version is a draft':'Published'}</p></div><button className="button secondary" onClick={()=>edit(j)}>Edit</button><button className="button secondary" disabled={busy} onClick={()=>send({action:'visibility',id:j.id,hidden:!data.hidden.includes(j.id)})}>{data.hidden.includes(j.id)?'Publish':'Unpublish'}</button></div>)}</div>
 {draft&&<div className="journey-editor"><div className="admin-section-heading"><h3>{draft.title}</h3><button className="text-button" onClick={()=>setDraft(null)}><X/> Close editor</button></div><div className="form-grid"><label>Journey ID<input value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value})}/></label><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Capability<Picker label="Capability" value={draft.capability} options={Object.entries(capabilityLabels).map(([value,label])=>({value,label}))} onChange={v=>setDraft({...draft,capability:v as Capability})}/></label><label>Starting step<Picker label="Starting step" value={draft.start} options={draft.steps.map(s=>({value:s.id,label:s.question}))} onChange={v=>setDraft({...draft,start:v})}/></label></div>
 {draft.steps.map((s,i)=><fieldset className="step-editor" key={s.id}><legend>Step {i+1} · {s.id}</legend><div className="inline-actions"><button className="button secondary" disabled={!i} onClick={()=>move(i,-1)}><ArrowUp/> Move up</button><button className="button secondary" disabled={i===draft.steps.length-1} onClick={()=>move(i,1)}><ArrowDown/> Move down</button><button className="button secondary" onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,n)=>n!==i)})}>Remove step</button></div><label>Question<input value={s.question} onChange={e=>changeStep(i,{question:e.target.value})}/></label><label className="allow-input">Allow optional written answer<Switch className="comfort-switch" checked={!!s.allowInput} onCheckedChange={v=>changeStep(i,{allowInput:v})}/></label><label>Default next step<Picker label={`Next step after ${s.question}`} value={s.next||'create'} options={[...draft.steps.filter(x=>x.id!==s.id).map(x=>({value:x.id,label:x.question})),{value:'create',label:'Create the result'}]} onChange={v=>changeStep(i,{next:v})}/></label>
 {s.options.map((o,n)=><div className="option-editor" key={`${s.id}-${n}`}><label>Choice {n+1}<input value={o.label} onChange={e=>changeStep(i,{options:s.options.map((x,k)=>k===n?{...x,label:e.target.value}:x)})}/></label><label>Then go to<Picker label={`Branch for ${o.label}`} value={o.next||''} options={[{value:'',label:'Default next step'},...draft.steps.filter(x=>x.id!==s.id).map(x=>({value:x.id,label:x.question})),{value:'create',label:'Create the result'}]} onChange={v=>changeStep(i,{options:s.options.map((x,k)=>k===n?{...x,next:v||undefined}:x)})}/></label><button className="button secondary" aria-label={`Remove choice ${n+1}`} onClick={()=>changeStep(i,{options:s.options.filter((_,k)=>k!==n)})}><X/></button></div>)}<button className="button secondary" disabled={s.options.length>=8} onClick={()=>changeStep(i,{options:[...s.options,{id:`choice-${Date.now()}`,label:'New choice',icon:'sun'}]})}><Plus/> Add choice</button></fieldset>)}
 <button className="button secondary" onClick={()=>setDraft({...draft,steps:[...draft.steps,{id:`step-${Date.now()}`,question:'What sounds good?',next:'create',options:[{id:'one',label:'First choice'},{id:'two',label:'Second choice'}]}]})}><Plus/> Add a step</button>
 <label>Generation instructions<textarea value={draft.instruction} onChange={e=>setDraft({...draft,instruction:e.target.value})}/></label><label>Refinement labels (one per line)<textarea value={draft.refinements.map(r=>r.label).join('\n')} onChange={e=>setDraft({...draft,refinements:e.target.value.split('\n').filter(Boolean).map((label,i)=>({id:draft.refinements[i]?.id||`refine-${i}`,label,icon:draft.refinements[i]?.icon||'refresh'}))})}/></label>
 <div className="inline-actions"><button className="button secondary" onClick={beginPreview}><Eye/> Preview journey</button><button className="button secondary" disabled={busy} onClick={()=>send({action:'save',journey:draft,publish:false})}><Save/> Save draft</button><button className="button" disabled={busy} onClick={()=>send({action:'save',journey:draft,publish:true})}>Save & publish</button></div><p className="setting-note">Published versions are immutable. Existing projects keep their original journey. Move controls reorder the editor; use branch destinations to change the sequence.</p></div>}
 </section><section className="admin-section"><h2>Recent generation activity</h2><p>Operational metadata only. Private creation content is not displayed here.</p>{!data?.logs.length?<p className="setting-note">Activity will appear after the first creation.</p>:<div className="generation-log">{data.logs.map((l,i)=><div key={i}><strong>{capabilityLabels[l.capability as Capability]}</strong><span>{l.status} · {l.provider}</span><time>{new Date(l.created_at).toLocaleString()}</time>{l.error&&<p>{l.error}</p>}</div>)}</div>}</section></main>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="preview-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle className="dialog-title">Journey preview</DialogTitle><button className="settings-button" onClick={()=>setPreview(false)} aria-label="Close preview"><X/></button></div><DialogDescription>Uses the same guide as the studio. No generation request will be sent.</DialogDescription>{draft&&session&&<Guide key={session.node} journey={draft} session={session} busy={false} available={false} preview onChoose={(id,input)=>setSession(choose(draft,session,id,input))} onBack={()=>setSession(goBack(draft,session))} onGenerate={()=>{setMessage('Preview complete. The result uses the shared review, revision, and output controls.');setPreview(false);}}/>}</DialogContent></Dialog>
 </div>;
}
