'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,ArrowRight,Check,Download,Heart,LoaderCircle,Music2,Printer,Shuffle,SlidersHorizontal,Volume2,X } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import Guide,{ChoiceIcon} from './guide';
import Player from './player';
import Coloring from './coloring';
import { journeys as builtins } from '@/lib/creative/journeys';
import type { Artifact,Project,StudioData } from '@/lib/creative/types';
type View='home'|'guide'|'creations'|'ideas'|'coloring';
const empty:StudioData={journeys:builtins,projects:[],availability:{generate_music:false,generate_text:false,generate_image:false,create_printable:false},isAdmin:false,signedIn:false};
async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json() as StudioData & {project:Project;error?:string};if(!r.ok)throw new Error(data.error||'That didn’t work. Please try again.');return data;}
export default function Studio(){
 const [data,setData]=useState<StudioData>(empty),[view,setView]=useState<View>('home'),[project,setProject]=useState<Project|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[settings,setSettings]=useState(false),[large,setLarge]=useState(false),[reduced,setReduced]=useState(false),[speaking,setSpeaking]=useState(false),[canSpeak,setCanSpeak]=useState(false);
 const [coloringSource,setColoringSource]=useState<Artifact|undefined>();
 const locked=useRef(false),requestKey=useRef<string|null>(null),mounted=useRef(true);
 function place(p:Project){setProject(p);setData(d=>({...d,projects:[p,...d.projects.filter(x=>x.id!==p.id)]}));}
 async function refresh(){setLoading(true);try{const d=await api('/api/studio');setData(d);const id=new URLSearchParams(window.location.search).get('project');if(id){const found=d.projects.find((p:Project)=>p.id===id);if(found){setProject(found);setView('guide');}}setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{mounted.current=true;void refresh();setCanSpeak('speechSynthesis' in window);try{const v=JSON.parse(localStorage.getItem('creative-comfort')||'{}');setLarge(!!v.large);setReduced(!!v.reduced);}catch{}return()=>{mounted.current=false;window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{document.documentElement.style.fontSize=large?'20px':'16px';document.documentElement.dataset.reducedMotion=String(reduced);try{localStorage.setItem('creative-comfort',JSON.stringify({large,reduced}));}catch{}},[large,reduced]);
 useEffect(()=>{window.speechSynthesis?.cancel();setSpeaking(false);const t=setTimeout(()=>{document.getElementById('screen-heading')?.focus({preventScroll:true});},50);return()=>clearTimeout(t);},[view,project?.session.node,project?.activeArtifactId]);
 useEffect(()=>{if(project?.status!=='generating'||busy)return;const t=setInterval(()=>{api(`/api/studio?project=${project.id}`).then(d=>place(d.project)).catch(()=>{});},5000);return()=>clearInterval(t);},[project?.id,project?.status,busy]);
 async function run(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{locked.current=false;if(mounted.current)setBusy(false);}}
 function navigate(v:View){setView(v);setError('');setNotice('');window.history.replaceState(null,'','/');window.scrollTo(0,0);}
 function start(id:string,fromProject?:string){void run(async()=>{const d=await api('/api/studio',{action:'start',journeyId:id,fromProject,requestKey:crypto.randomUUID()});place(d.project);setView('guide');window.history.replaceState(null,'',`/?project=${d.project.id}`);window.scrollTo(0,0);});}
 function open(p:Project){place(p);setView('guide');setError('');window.history.replaceState(null,'',`/?project=${p.id}`);window.scrollTo(0,0);}
 function act(action:string,extra:Record<string,unknown>={}){if(!project)return;void run(async()=>{const d=await api('/api/studio',{action,projectId:project.id,version:project.version,...extra});place(d.project);if(action==='keep')setNotice('Kept in My creations. Only you can see it.');});}
 function make(sample:boolean,change=''){if(!project)return;void run(async()=>{requestKey.current=crypto.randomUUID();setProject({...project,status:'generating'});try{const d=await api('/api/generate',{projectId:project.id,version:project.version,requestKey:requestKey.current,sample,change});place(d.project);}catch(e){const d=await api(`/api/studio?project=${project.id}`);place(d.project);throw e;}});}
 function read(text:string){if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}const speech=new SpeechSynthesisUtterance(text);speech.rate=.9;speech.onend=()=>setSpeaking(false);speech.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(speech);}
 function download(a:Artifact){if(a.media){const link=document.createElement('a');link.href=a.media+'&download=1';link.download='my-creation';link.click();return;}const blob=new Blob([a.text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${a.title.replace(/[^a-zA-Z0-9 -]/g,'')||'my-creation'}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const a=project?.artifacts.find(a=>a.id===project.activeArtifactId)||project?.artifacts.at(-1);const isReview=project&&a&&['review','complete'].includes(project.status);const songs=data.journeys.find(j=>j.id==='song'),stories=data.journeys.find(j=>j.id==='story');
 return <div className="studio" aria-busy={busy}>
 <a className="skip-link" href="#main">Skip to creating</a>
 <header className="site-header"><button className="wordmark" onClick={()=>navigate('home')}>creative<br/><span>companion.</span></button><nav aria-label="Main"><button className={`nav-link ${view==='home'?'active':''}`} onClick={()=>navigate('home')}>The studio</button><button className={`nav-link ${view==='creations'?'active':''}`} onClick={()=>navigate('creations')}><Heart size={22}/> My creations</button><button className={`nav-link ideas-nav ${view==='ideas'?'active':''}`} onClick={()=>navigate('ideas')}>A little inspiration</button></nav><button className="settings-button" aria-label="Comfort settings" onClick={()=>setSettings(true)}><SlidersHorizontal/></button></header>
 <main id="main" className="main-content">
 {error&&<div className="error-notice" role="alert"><p>{error}</p><div className="inline-actions">{!data.signedIn&&!loading?<a className="button" href="/login?returnTo=%2F">Sign in</a>:<button className="button secondary" onClick={()=>project?void run(async()=>{const d=await api(`/api/studio?project=${project.id}`);place(d.project);}):void refresh()}>Check again</button>}<button className="button secondary" onClick={()=>navigate('home')}>Try something different</button></div></div>}
 {notice&&<output className="success-notice"><Check/>{notice}</output>}
 {view==='home'&&<><div className="welcome"><div><p className="eyebrow">A LITTLE CURIOSITY. ENDLESS POSSIBILITIES.</p><h1 tabIndex={-1} id="screen-heading">What shall we make?</h1><p className="intro">Pick something you’d love to try. We’ll make it together.</p></div><span className="studio-note">Your imagination<br/>belongs here.</span></div>
 <div className="featured-journeys">{songs&&<button disabled={busy||loading||!data.signedIn} className="journey-feature song-feature" onClick={()=>start('song')}><div className="feature-art music-art"><div className="music-composition" aria-hidden="true"><Music2 size={92} strokeWidth={1.2}/><span className="music-word">a little<br/><em>melody.</em></span></div><span className="label-sticker">A song that’s yours</span></div><div className="feature-copy"><div><span className="eyebrow">START WITH A FEELING</span><h2>Make a song</h2><p>{songs.description}</p></div><span className="round-arrow"><ArrowRight/></span></div></button>}{stories&&<button disabled={busy||loading||!data.signedIn} className="journey-feature story-feature" onClick={()=>start('story')}><div className="feature-art story-art"><img src="/artwork/moonlit-fox.png" alt="A fox exploring a moonlit garden"/><span className="label-sticker">Where will your story go?</span></div><div className="feature-copy"><div><span className="eyebrow">FOLLOW YOUR IMAGINATION</span><h2>Write a story</h2><p>{stories.description}</p></div><span className="round-arrow"><ArrowRight/></span></div></button>}</div>
 <div className="other-journeys"><button disabled={busy||loading||!data.signedIn} onClick={()=>{setColoringSource(undefined);navigate('coloring');}}><ChoiceIcon name="palette" size={26}/><span>Make a coloring page</span><ArrowRight/></button>{data.journeys.filter(j=>!['song','story'].includes(j.id)).map(j=><button disabled={busy||loading||!data.signedIn} key={j.id} onClick={()=>start(j.id)}><ChoiceIcon name={j.icon} size={26}/><span>{j.title}</span><ArrowRight/></button>)}<button disabled={busy||loading||!data.signedIn||!data.journeys.length} className="surprise" onClick={()=>start(data.journeys[crypto.getRandomValues(new Uint32Array(1))[0]%data.journeys.length].id)}><Shuffle/><span>Surprise me</span><ArrowRight/></button></div>
 {loading&&<output className="loading-note">Opening your studio…</output>}
 {data.projects.some(p=>!p.kept)&&<section className="continue-section"><h3>Right where you left off</h3>{data.projects.filter(p=>!p.kept).slice(0,2).map(p=><button key={p.id} className="resume-button" onClick={()=>open(p)}><ChoiceIcon name={p.journey.icon}/><span>{p.title}<small>{p.artifacts.length?'Come back to your creation':'Your choices are saved'}</small></span><ArrowRight/></button>)}</section>}
 </>}
 {view==='coloring'&&<Coloring projects={data.projects} available={data.availability.generate_image} initial={coloringSource} onBack={()=>{navigate('home');void refresh();}}/>}
 {view==='guide'&&project&&<>
 {project.status==='generating'?<section className="waiting"><LoaderCircle className="slow-spin" size={64}/><h1 tabIndex={-1} id="screen-heading">Making room for a little magic.</h1><p role="status">{project.journey.capability==='generate_music'?'Your song is coming together. This may take a few minutes.':'Your creation is coming together. This may take a moment.'}</p><p>Your choices are saved. You can come back here from My creations.</p><div className="inline-actions"><button className="button secondary" onClick={()=>navigate('home')}>Back to the studio</button>{!busy&&<button className="button secondary" onClick={()=>act('check')}>Check on my creation</button>}</div></section>:
 isReview&&a?<section className="review"><div className="guide-topline"><button className="text-button" onClick={()=>navigate('home')}><ArrowLeft/> The studio</button><span className="eyebrow">{a.sample?'PRACTICE CREATION':'MADE BY YOU'}</span><span className="step-label">Version {a.revision}</span></div><div className="review-heading"><h1 tabIndex={-1} id="screen-heading">{project.kept?'Look what you made.':'What do you think?'}</h1><p>{a.sample?'Explore the experience with this practice version.':'Something that started with your imagination.'}</p></div>
 {a.sample&&<div className="practice-notice"><strong>{a.kind==='music'?'Instrumental sketch • no sung vocals':'Prepared example • not a new AI creation'}</strong><p>{a.kind==='music'?'The music is a simple computer-composed sketch. The lyric idea below uses prepared lines. Full sung songs will be available after the music service is connected.':'This example lets you try keeping, reviewing, and printing. Live creation will follow your choices once connected.'}</p></div>}
 <div className={`result-layout ${a.kind==='image'?'image-result':''}`}><div className={`artifact-paper ${a.kind}`} id="print-artifact">{a.kind==='music'?<><div className="song-heading"><Music2 size={46}/><div><span className="eyebrow">YOUR LITTLE RECORDING</span><h2>{a.title}</h2></div></div>{a.media&&<Player key={a.id} src={a.media}/>}</>:a.kind==='image'?<img className="result-image" src={a.media||a.image} alt={a.sample?'Prepared artwork example':a.title}/>:<>{a.kind==='printable'&&a.image&&<img className="print-border" src={a.image} alt=""/>}<h2>{a.title}</h2></>}{a.text&&<div className="artifact-text">{(a.kind==='image'?a.text:a.text.split('\n').slice(1).join('\n')).split(/\n\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</div>}</div>
 <aside className="review-actions">{a.kind==='image'&&<button className="button secondary" disabled={busy} onClick={()=>{setColoringSource(a);navigate('coloring');}}>Turn into a coloring page</button>}<button className="button keep-button" disabled={busy} onClick={()=>act('keep')}><Heart fill={project.kept?'currentColor':'none'}/>{project.kept?'Kept in My creations':'I love it. Keep this.'}</button><p className="action-caption">Want to change something?</p>{project.journey.refinements.map(r=><button className="button secondary" disabled={busy} key={r.id} onClick={()=>make(a.sample,r.id)}><ChoiceIcon name={r.icon} size={24}/>{r.label}</button>)}<button className="button secondary" disabled={busy} onClick={()=>act('back')}><ArrowLeft/> Change my choices</button><div className="output-actions"><button className="button secondary" onClick={()=>download(a)}><Download/>{a.media?'Download':'Download words'}</button>{a.kind!=='music'&&<button className="button secondary" onClick={()=>window.print()}><Printer/> Print / save PDF</button>}{a.text&&canSpeak&&<button className="button secondary" onClick={()=>read(a.text)}><Volume2/>{speaking?'Stop reading':'Read it aloud'}</button>}</div></aside></div>
 {project.artifacts.length>1&&<div className="revision-history"><h3>Your versions</h3><div>{project.artifacts.map(r=><button className={`button secondary ${r.id===a.id?'selected-version':''}`} disabled={busy} key={r.id} onClick={()=>act('restore',{artifactId:r.id})}>{r.id===a.id&&<Check/>}Version {r.revision}</button>)}</div></div>}
 <section className="next-possibility"><p className="eyebrow">YOUR NEXT LITTLE ADVENTURE</p><h2>What else could this become?</h2><div className="related-choices">{project.journey.related.map(id=>data.journeys.find(j=>j.id===id)).filter(Boolean).map(j=><button className="button secondary" key={j!.id} onClick={()=>start(j!.id,project.id)}><ChoiceIcon name={j!.icon} size={24}/>{project.journey.id==='song'&&j!.id==='story'?'Turn this into a story':j!.title}<ArrowRight/></button>)}</div></section>
 </section>:<><Guide key={project.session.node} journey={project.journey} session={project.session} busy={busy} available={data.availability[project.journey.capability]} onChoose={(choiceId,input)=>act('choose',{choiceId,input})} onBack={()=>project.session.history.length?act('back'):navigate('home')} onGenerate={sample=>make(sample)}/>{project.status==='failed'&&<p className="error-notice" role="alert">{project.error||'That one didn’t work. Your choices are saved. You can try again above.'}</p>}</>}
 </>}
 {view==='creations'&&<><div className="welcome"><div><p className="eyebrow">A LITTLE COLLECTION OF YOU</p><h1 tabIndex={-1} id="screen-heading">My creations</h1><p className="intro">Your ideas, your versions, your happy accidents. Private to you.</p><button className="button secondary" onClick={()=>{setColoringSource(undefined);navigate('coloring');}}>My coloring pages <ArrowRight/></button></div></div>{!data.projects.length?<div className="empty-state"><Heart size={56}/><h2>Something wonderful starts here.</h2><p>When you make something, we’ll keep it here for you.</p><button className="button" onClick={()=>navigate('home')}>Make something <ArrowRight/></button></div>:<div className="creations-grid">{data.projects.map(p=>{const art=p.artifacts.find(a=>a.id===p.activeArtifactId)||p.artifacts.at(-1);return <button className="creation-card" key={p.id} onClick={()=>open(p)}><div className={`creation-thumbnail ${art?.kind==='music'?'music-art':''}`}>{art?.kind==='image'?<img src={art.media||art.image} alt=""/>:<ChoiceIcon name={p.journey.icon} size={62}/>}</div><div className="creation-copy"><p className="eyebrow">{art?.sample?'PRACTICE · ':''}{p.kept?'KEPT':p.status==='generating'?'COMING TOGETHER':art?'READY TO EXPLORE':'IN PROGRESS'}</p><h3>{p.title}</h3><span>{p.journey.title} <ArrowRight size={20}/></span></div></button>;})}</div>}</>}
 {view==='ideas'&&<><div className="welcome"><div><p className="eyebrow">FROM THE STUDIO COLLECTION</p><h1 tabIndex={-1} id="screen-heading">A little inspiration.</h1><p className="intro">Prepared examples to set your imagination wandering.</p></div></div><div className="creations-grid">{[{id:'art',image:'watercolor-elephant',title:'A gentle giant in watercolor'},{id:'story',image:'moonlit-fox',title:'A visitor in the moonlit garden'},{id:'card',image:'botanical-card',title:'A little color for someone you love'}].map(i=><button className="creation-card" key={i.id} disabled={busy||!data.signedIn} onClick={()=>start(i.id)}><div className="inspiration-image"><img src={`/artwork/${i.image}.png`} alt={i.title}/></div><div className="creation-copy"><h3>{i.title}</h3><span>Make something like this <ArrowRight size={20}/></span></div></button>)}</div></>}
 <footer className="studio-footer"><span>One choice at a time. A world of things to make.</span>{data.isAdmin?<a href="/admin">Manage the studio <ArrowRight size={16}/></a>:<span>Made for your imagination</span>}</footer>
 </main>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="comfort-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle className="dialog-title">Make yourself comfortable.</DialogTitle><button className="settings-button" aria-label="Close comfort settings" onClick={()=>setSettings(false)}><X/></button></div><DialogDescription className="dialog-description">A few small changes to make the studio feel right for you.</DialogDescription><label className="comfort-row" htmlFor="large-text"><span>Larger words</span><Switch id="large-text" className="comfort-switch" checked={large} onCheckedChange={setLarge}/></label><label className="comfort-row" htmlFor="less-motion"><span>Less movement</span><Switch id="less-motion" className="comfort-switch" checked={reduced} onCheckedChange={setReduced}/></label><p className="setting-note">Saved on this device. You can also use your browser’s zoom controls.</p><button className="button" onClick={()=>setSettings(false)}>That feels right <Check/></button></DialogContent></Dialog>
 </div>;
}
