import { index, integer, pgTable, text, uniqueIndex } from 'drizzle-orm/pg-core';

export const projects=pgTable('projects',{id:text('id').primaryKey(),owner:text('owner').notNull(),title:text('title').notNull(),journey:text('journey').notNull(),session:text('session').notNull(),status:text('status').notNull(),kept:integer('kept').notNull().default(0),activeArtifactId:text('active_artifact_id'),version:integer('version').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('projects_owner_updated').on(t.owner,t.updatedAt)]);
export const artifacts=pgTable('artifacts',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),payload:text('payload').notNull(),storageKey:text('storage_key'),createdAt:text('created_at').notNull()},t=>[index('artifacts_project').on(t.projectId)]);
export const generations=pgTable('generations',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),owner:text('owner').notNull(),requestKey:text('request_key').notNull(),status:text('status').notNull(),capability:text('capability').notNull(),provider:text('provider').notNull(),input:text('input').notNull(),artifactId:text('artifact_id'),error:text('error'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('generations_request_key').on(t.owner,t.requestKey),index('generations_project').on(t.projectId),index('generations_owner_created').on(t.owner,t.createdAt)]);
export const events=pgTable('interaction_events',{id:text('id').primaryKey(),owner:text('owner').notNull(),projectId:text('project_id'),type:text('type').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_project').on(t.projectId)]);
export const journeyVersions=pgTable('journey_versions',{id:text('id').primaryKey(),journeyId:text('journey_id').notNull(),version:integer('version').notNull(),definition:text('definition').notNull(),published:integer('published').notNull().default(0),createdAt:text('created_at').notNull()},t=>[uniqueIndex('journey_version_unique').on(t.journeyId,t.version)]);
export const journeySettings=pgTable('journey_settings',{journeyId:text('journey_id').primaryKey(),hidden:integer('hidden').notNull().default(0)});
export const preferences=pgTable('preferences',{owner:text('owner').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});
