import { body,db,eventStatement,failure,getProject,json,protectMutation,PublicError,runtime,user } from '@/lib/creative/server';
import { generate } from '@/lib/creative/providers';
import type { Artifact } from '@/lib/creative/types';
export const dynamic='force-dynamic';
export async function POST(request:Request){let generationId:string|undefined;let projectId:string|undefined;let owner:string|undefined;try{protectMutation(request);const u=await user();owner=u.userId;const b=await body(request);const p=await getProject(String(b.projectId),owner);projectId=p.id;
 if(typeof b.requestKey!=='string'||!/^[a-f0-9-]{36}$/.test(b.requestKey))throw new PublicError('Please try again from the studio.');
 const prior=await db().prepare('SELECT id,status FROM generations WHERE owner=? AND request_key=?').bind(owner,b.requestKey).first();if(prior)return json({project:await getProject(p.id,owner)});
 if(p.version!==b.version||p.status==='generating')throw new PublicError('This creation is already being updated. Please check it again.',409);
 if(p.session.node!=='create')throw new PublicError('Let’s finish choosing first.');
 const change=typeof b.change==='string'?b.change:'';if(change&&!p.journey.refinements.some(r=>r.id===change))throw new PublicError('Please choose one of the changes shown.');
 const count=await db().prepare('SELECT COUNT(*) AS n FROM generations WHERE owner=? AND created_at>?').bind(owner,new Date(Date.now()-86400000).toISOString()).first<{n:number}>();if((count?.n||0)>=30)throw new PublicError('The studio has made its creations for today. Your work is safe. Come back tomorrow.',429);
 const now=new Date().toISOString();generationId=crypto.randomUUID();const claimed=await db().prepare('UPDATE projects SET status=?,version=version+1,updated_at=? WHERE id=? AND owner=? AND version=? AND status!=?').bind('generating',now,p.id,owner,p.version,'generating').run();if(!claimed.meta.changes)throw new PublicError('This creation is already being updated.',409);
 await db().batch([db().prepare('INSERT INTO generations (id,project_id,owner,request_key,status,capability,provider,input,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(generationId,p.id,owner,b.requestKey,'running',p.journey.capability,b.sample===true?'practice':'configured',JSON.stringify({session:p.session,change,sample:b.sample===true}),now,now),eventStatement(owner,p.id,change?'refinement_requested':'generation_requested',{sample:b.sample===true,change})]);
 const previous=p.artifacts.find(a=>a.id===p.activeArtifactId);const result=await generate(p,b.sample===true,change,previous);const artifactId=crypto.randomUUID();let storageKey:string|null=null;
 if(result.bytes){storageKey=`artifacts/${p.id}/${artifactId}`;await runtime().FILES.put(storageKey,result.bytes,{httpMetadata:{contentType:result.mime||'application/octet-stream'}});}
 const artifact:Artifact={id:artifactId,projectId:p.id,title:result.title,text:result.text,kind:result.kind,sample:b.sample===true,revision:p.artifacts.length+1,createdAt:new Date().toISOString(),selections:p.session.history,...(previous?{parentId:previous.id}:{}),...(change?{change}:{}),...(result.image?{image:result.image}:{}),...(storageKey?{media:`/api/media?id=${artifactId}`,mime:result.mime}:{})};
 await db().batch([db().prepare('INSERT INTO artifacts (id,project_id,payload,storage_key,created_at) VALUES (?,?,?,?,?)').bind(artifactId,p.id,JSON.stringify(artifact),storageKey,artifact.createdAt),db().prepare('UPDATE projects SET title=?,status=?,active_artifact_id=?,version=version+1,updated_at=? WHERE id=? AND owner=?').bind(result.title,'review',artifactId,artifact.createdAt,p.id,owner),db().prepare('UPDATE generations SET status=?,provider=?,artifact_id=?,updated_at=? WHERE id=?').bind('succeeded',result.provider,artifactId,artifact.createdAt,generationId),eventStatement(owner,p.id,'artifact_created',{artifactId,sample:artifact.sample})]);return json({project:await getProject(p.id,owner)});
 }catch(e){if(generationId&&projectId&&owner){const message=e instanceof PublicError?e.message:'The connection was interrupted. Your choices are saved.';await db().batch([db().prepare('UPDATE generations SET status=?,error=?,updated_at=? WHERE id=?').bind('failed',message,new Date().toISOString(),generationId),db().prepare('UPDATE projects SET status=?,version=version+1 WHERE id=? AND owner=? AND status=?').bind('failed',projectId,owner,'generating')]).catch(()=>{});}return failure(e);}}
