import { admin,availability,body,db,encrypt,eventStatement,failure,getJourneys,json,protectMutation,PublicError,runtime } from '@/lib/creative/server';
import { validateJourney } from '@/lib/creative/engine';
export const dynamic='force-dynamic';
export async function GET(){try{await admin();const versions=await db().prepare('SELECT journey_id,version,published FROM journey_versions ORDER BY version DESC').all();const hidden=await db().prepare('SELECT journey_id FROM journey_settings WHERE hidden=1').all<{journey_id:string}>();const logs=await db().prepare('SELECT capability,provider,status,error,created_at FROM generations ORDER BY created_at DESC LIMIT 30').all();return json({journeys:await getJourneys(true),versions:versions.results,hidden:hidden.results.map(h=>h.journey_id),availability:await availability(),secureSetup:!!runtime().APP_ENCRYPTION_KEY,logs:logs.results});}catch(e){return failure(e);}}
export async function POST(request:Request){try{protectMutation(request);const u=await admin(),b=await body(request),now=new Date().toISOString();
 if(b.action==='provider'){if(!['openai-text','openai-image','suno','elevenlabs'].includes(b.id))throw new PublicError('Choose a supported provider.');if(typeof b.key!=='string'||b.key.length<10||b.key.length>1000)throw new PublicError('Enter a valid provider key.');if(typeof b.model!=='string'||!/^[a-zA-Z0-9_.:-]{1,100}$/.test(b.model))throw new PublicError('Enter a model identifier.');await db().batch([db().prepare('INSERT INTO provider_settings (id,encrypted_key,model,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET encrypted_key=excluded.encrypted_key,model=excluded.model,updated_at=excluded.updated_at').bind(b.id,await encrypt(b.key),b.model,now),eventStatement(u.userId,null,'provider_configured',{provider:b.id})]);return json({ok:true});}
 if(b.action==='disconnect'){if(!['openai-text','openai-image','suno','elevenlabs'].includes(b.id))throw new PublicError('Choose a supported provider.');await db().prepare('DELETE FROM provider_settings WHERE id=?').bind(b.id).run();return json({ok:true});}
 if(b.action==='visibility'){if(typeof b.id!=='string')throw new PublicError('Choose a journey.');await db().prepare('INSERT INTO journey_settings (journey_id,hidden) VALUES (?,?) ON CONFLICT(journey_id) DO UPDATE SET hidden=excluded.hidden').bind(b.id,b.hidden?1:0).run();return json({ok:true});}
 if(b.action==='save'){const errors=validateJourney(b.journey);if(errors.length)throw new PublicError(errors.join(' '));const j=b.journey;const latest=await db().prepare('SELECT MAX(version) AS version FROM journey_versions WHERE journey_id=?').bind(j.id).first<{version:number|null}>();j.version=Math.max(latest?.version||0,1)+1;
 const statements=[db().prepare('INSERT INTO journey_versions (id,journey_id,version,definition,published,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),j.id,j.version,JSON.stringify(j),b.publish?1:0,now),eventStatement(u.userId,null,b.publish?'journey_published':'journey_draft_saved',{journeyId:j.id,version:j.version})];if(b.publish)statements.push(db().prepare('INSERT INTO journey_settings (journey_id,hidden) VALUES (?,0) ON CONFLICT(journey_id) DO UPDATE SET hidden=0').bind(j.id));await db().batch(statements);return json({ok:true,journey:j});}
 throw new PublicError('Choose an action.');}catch(e){return failure(e);}}
