import { admin,availability,body,db,eventStatement,failure,getJourneys,json,protectMutation,PublicError } from '@/lib/creative/server';
import { validateJourney } from '@/lib/creative/engine';
export const dynamic='force-dynamic';
export async function GET(){try{await admin();const versions=await db().prepare('SELECT journey_id,version,published FROM journey_versions ORDER BY version DESC').all();const hidden=await db().prepare('SELECT journey_id FROM journey_settings WHERE hidden=1').all<{journey_id:string}>();const logs=await db().prepare('SELECT capability,provider,status,error,created_at FROM generations ORDER BY created_at DESC LIMIT 30').all();return json({journeys:await getJourneys(true),versions:versions.results,hidden:hidden.results.map(h=>h.journey_id),availability:await availability(),logs:logs.results});}catch(e){return failure(e);}}
export async function POST(request:Request){try{protectMutation(request);const u=await admin(),b=await body(request),now=new Date().toISOString();
 if(b.action==='visibility'){if(typeof b.id!=='string')throw new PublicError('Choose a journey.');await db().prepare('INSERT INTO journey_settings (journey_id,hidden) VALUES (?,?) ON CONFLICT(journey_id) DO UPDATE SET hidden=excluded.hidden').bind(b.id,b.hidden?1:0).run();return json({ok:true});}
 if(b.action==='save'){const errors=validateJourney(b.journey);if(errors.length)throw new PublicError(errors.join(' '));const j=b.journey;const latest=await db().prepare('SELECT MAX(version) AS version FROM journey_versions WHERE journey_id=?').bind(j.id).first<{version:number|null}>();j.version=Math.max(latest?.version||0,1)+1;
 const statements=[db().prepare('INSERT INTO journey_versions (id,journey_id,version,definition,published,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),j.id,j.version,JSON.stringify(j),b.publish?1:0,now),eventStatement(u.userId,null,b.publish?'journey_published':'journey_draft_saved',{journeyId:j.id,version:j.version})];if(b.publish)statements.push(db().prepare('INSERT INTO journey_settings (journey_id,hidden) VALUES (?,0) ON CONFLICT(journey_id) DO UPDATE SET hidden=0').bind(j.id));await db().batch(statements);return json({ok:true,journey:j});}
 throw new PublicError('Choose an action.');}catch(e){return failure(e);}}
